apis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
	
	path('', views.AccountView.as_view(), name="account"),
	path('profile', views.profile_view, name="profile"),
	path('sign-up', views.SignUpView.as_view(), name="sign-up"),
	path('sign-in', views.SignInView.as_view(), name="sign-in"),
	path('sign-out', views.sign_out, name="sign-out"),
	]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	'''
	Our UserProfile model extends the built-in Django User Model
	'''
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	
	address = models.CharField(verbose_name="Address",max_length=100, null=True, blank=True)
	town = models.CharField(verbose_name="Town/City",max_length=100, null=True, blank=True)
	county = models.CharField(verbose_name="County",max_length=100, null=True, blank=True)
	post_code = models.CharField(verbose_name="Post Code",max_length=8, null=True, blank=True)
	country = models.CharField(verbose_name="Country",max_length=100, null=True, blank=True)
	longitude = models.CharField(verbose_name="Longitude",max_length=50, null=True, blank=True)
	latitude = models.CharField(verbose_name="Latitude",max_length=50, null=True, blank=True)

	captcha_score = models.FloatField(default = 0.0)
	has_profile = models.BooleanField(default = False)
	
	is_active = models.BooleanField(default = True)

	def __str__(self):
		return f'{self.user}'

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile


class UserForm(UserCreationForm):
	'''
	Form that uses built-in UserCreationForm to handel user creation
	'''
	first_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your first name..'}))
	last_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your last name..'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password..','class':'password'}))

	#reCAPTCHA token
	token = forms.CharField(
		widget=forms.HiddenInput())

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )


class AuthForm(AuthenticationForm):
	'''
	Form that uses built-in AuthenticationForm to handel user auth
	'''
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username','password', )


class UserProfileForm(forms.ModelForm):
	'''
	Basic model-form for our user profile that extends Django user model.
	
	'''
	address = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	town = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	county = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	post_code = forms.CharField(max_length=8, required=True, widget = forms.HiddenInput())
	country = forms.CharField(max_length=40, required=True, widget = forms.HiddenInput())
	longitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())
	latitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())


	class Meta:
		model = UserProfile
		fields = ('address', 'town', 'county', 'post_code',
		 'country', 'longitude', 'latitude')

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.http import JsonResponse
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator


from apis.mixins import(
	AjaxFormMixin, 
	reCAPTCHAValidation,
	FormErrors,
	RedirectParams,
	)


from .forms import (
	UserForm,
	UserProfileForm,
	AuthForm,
	)

result = "Error"
message = "There was an error, please try again"


class AccountView(TemplateView):
	'''
	Generic FormView with our mixin to display user account page
	'''
	template_name = "users/account.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)


def profile_view(request):
	'''
	function view to allow users to update their profile
	'''
	user = request.user
	up = user.userprofile

	form = UserProfileForm(instance = up) 

	if request.is_ajax():
		form = UserProfileForm(data = request.POST, instance = up)
		if form.is_valid():
			obj = form.save()
			obj.has_profile = True
			obj.save()
			result = "Success"
			message = "Your profile has been updated"
		else:
			message = FormErrors(form)
		data = {'result': result, 'message': message}
		return JsonResponse(data)

	else:

		context = {'form': form}
		context['google_api_key'] = settings.GOOGLE_API_KEY
		context['base_country'] = settings.BASE_COUNTRY

		return render(request, 'users/profile.html', context)


class SignUpView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for user sign-up with reCAPTURE security
	'''

	template_name = "users/sign_up.html"
	form_class = UserForm
	success_url = "/"

	#reCAPTURE key required in context
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["recaptcha_site_key"] = settings.RECAPTCHA_PUBLIC_KEY
		return context

	#over write the mixin logic to get, check and save reCAPTURE score
	def form_valid(self, form):
		response = super(AjaxFormMixin, self).form_valid(form)	
		if self.request.is_ajax():
			token = form.cleaned_data.get('token')
			captcha = reCAPTCHAValidation(token)
			if captcha["success"]:
				obj = form.save()
				obj.email = obj.username
				obj.save()
				up = obj.userprofile
				up.captcha_score = float(captcha["score"])
				up.save()
				
				login(self.request, obj, backend='django.contrib.auth.backends.ModelBackend')

				#change result & message on success
				result = "Success"
				message = "Thank you for signing up"

				
			data = {'result': result, 'message': message}
			return JsonResponse(data)

		return response


class SignInView(AjaxFormMixin, FormView):
	'''
	Generic FormView with our mixin for user sign-in
	'''

	template_name = "users/sign_in.html"
	form_class = AuthForm
	success_url = "/"

	def form_valid(self, form):
		response = super(AjaxFormMixin, self).form_valid(form)	
		if self.request.is_ajax():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			#attempt to authenticate user
			user = authenticate(self.request, username=username, password=password)
			if user is not None:
				login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
				result = "Success"
				message = 'You are now logged in'
			else:
				message = FormErrors(form)
			data = {'result': result, 'message': message}
			return JsonResponse(data)
		return response


def sign_out(request):
	'''
	Basic view for user sign out
	'''
	logout(request)
	return redirect(reverse('users:sign-in'))

templates/users/account.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}


{% endblock %}


{% block content %}

<h3>Django Google API Course - User Account</h3>

<div class="container">

  <h4>User account details</h4>
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Username</td>
          <td>{{request.user.username}}</td>
      </tr>
      <tr>
        <td>Name</td>
        <td>{{request.user.first_name|title}} {{request.user.last_name|title}}</td>      
      </tr>


      {% if request.user.userprofile.has_profile %}

        <tr>
          <td>Address</td>
          <td>
            <address>
              {{request.user.userprofile.address}}<br>
              {{request.user.userprofile.town}}<br>
              {{request.user.userprofile.county}}<br>
              {{request.user.userprofile.post_code}}<br>
            </address>
          </td>      
        </tr>

      {% else %}
        <tr>
          <td>User Profile</td>
          <td><a href="{% url 'users:profile' %}" >Create user Profile</a></td>
        </tr>
      {% endif %}
    </tbody>
  </table>



</div>


{% endblock %}


{% block extend_footer %}

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block content %}

<h3>Django Google API Course - User Profile</h3>

<div class="container">
  {% if request.user.userprofile.has_profile %}
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Address</td>
        <td>
          <address>
            {{request.user.userprofile.address}}<br>
            {{request.user.userprofile.town}}<br>
            {{request.user.userprofile.county}}<br>
            {{request.user.userprofile.post_code}}<br>
          </address>
        </td>      
      </tr>
    </tbody>
  </table>
  </br>
  <label for="id-google-address">Change Address</label>
  {% else %}
  <label for="id-google-address">Add Address</label>
  {% endif %}

  <input type="text" placeholder="*Begin typing address" id="id-google-address" name="google_address">

  <form id="profileform" method="POST" action="/profile">
    {% csrf_token %}

   <label for="address" class="hidden-el" hidden>Address</label>
   {{form.address}}

   <label for="town" class="hidden-el" hidden>Town/City</label>
   {{form.town}}

   <label for="county" class="hidden-el" hidden>County</label>
   {{form.county}}

   <label for="post_code" class="hidden-el" hidden>Postal Code</label>
   {{form.post_code}}

   <label for="country" class="hidden-el" hidden>Country</label>
   {{form.country}}

   <label for="post_code" class="hidden-el" hidden>Longitude</label>
   {{form.longitude}}

   <label for="country"  class="hidden-el" hidden>Latitude</label>
   {{form.latitude}}


   <button disabled type="submit" id="profile-btn">Update</button>
 </form>

</div>

{% endblock %}

{% block extend_footer %}

<script type="text/javascript">

  var google_api_key = "{{google_api_key|safe}}";
  var base_country = "{{base_country|safe}}";

</script>

<script src="{% static 'google_places.js' %}"></script>


{% endblock %}

templates/users/sign_in.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block content %}

<h3>Django Google API Course - Sign In</h3>

<div class="container">

  <form id="signinform" method="POST" action="/sign-in">
    {% csrf_token %}
    <label for="username">Username</label>
    {{form.username}}

    <label for="password">Password</label>
    {{form.password}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Sign in</button>
 </form>

</div>

{% endblock %}


{% block extend_footer %}

{% endblock %}

templates/users/sign_out.html
{% extends 'base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

{% endblock %}

{% block content %}

<h3>Django Google API Course - Sign Up</h3>

<div class="container">


  <form id="signupform" method="POST" action="/sign-up">
    {% csrf_token %}

    
    <label for="first_name">First Name</label>
    {{form.first_name}}

    <label for="last_name">Last Name</label>
    {{form.last_name}}

    <label for="username">Username</label>
    {{form.username}}

    <label for="password1">Password</label>
    {{form.password1}}

    <label for="password2">Confirm Password</label>
    {{form.password2}}

    {{form.token}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
    </label>

    <button type="submit">Sign up</button>

  </form>
</div>


</div>

{% endblock %}

{% block extend_footer %}

<script type="text/javascript">
  // Create a variable that can be used in main.js
  var recaptcha_site_key = '{{recaptcha_site_key|safe}}'
</script>


{% endblock %}